---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
dictionaryDefinitions:
  - name: trezoaanchor-dictionary
    path: './.cspell-trezoaanchor-dictionary.txt'
    addWords: true
dictionaries:
  - trezoaanchor-dictionary
ignorePaths: []
